name: Test and Lint Python Package

env:
  DB_PROFILES: ${{ secrets.DB_PROFILES }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: html_publisher
    strategy:
      matrix:
        python-version: ["3.10"] 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies for pixels
      run: |
        python -m pip install --upgrade pip
        make dev
    - name: Run linting (linter, code style)
      run: make style
    - name: Run tests
      run: make test